### ISSUE TITLE
[Dynamic Contracts / Factories] throw ex; node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53

### ISSUE THREAD

**Issue by carlomigueldy** [enviodev/envio-hyperindexer-issues#3]
## Description

When registering a contract from the loader for dynamically created contracts by factory contracts throws this exception.

## Code

`config.yaml`
```yaml
name: limitless-markets-indexer
description: Limitless Markets Indexer
contracts:
  - name: LMSRMarketMakerFactory
    abi_file_path: ./abis/LMSRMarketMakerFactory.json
    handler: ./src/LMSRMarketMakerFactoryHandlers.ts
    events:
      - event: "LMSRMarketMakerCreation(address indexed creator, address lmsrMarketMaker, address pmSystem, address collateralToken, bytes32[] conditionIds, uint64 fee, uint funding)"
        requiredEntities:
          - name: "AutomatedMarketMaker"
  - name: LMSRMarketMaker
    abi_file_path: ./abis/LMSRMarketMaker.json
    handler: ./src/LMSRMarketMakerHandlers.ts
    events:
      - event: "AMMOutcomeTokenTrade(address indexed transactor, int[] outcomeTokenAmounts, int outcomeTokenNetCost, uint marketFees)"
        requiredEntities:
          - name: "AutomatedMarketMaker"
          - name: "Collateral"
          - name: "Trade"
networks:
  - id: 84532 # Base Sepolia Testnet
    start_block: 7583453
    contracts:
      - name: LMSRMarketMakerFactory
        address: "0x5DAA869eB10B10fefaDA22773cC8b30A8744df87"
```

`src/LMSRMarketMakerFactoryHandlers.ts`
```ts
import { LMSRMarketMakerFactoryContract_LMSRMarketMakerCreation_loader } from "../generated/src/Handlers.gen";

LMSRMarketMakerFactoryContract_LMSRMarketMakerCreation_loader(
  ({ event, context }) => {
    context.AutomatedMarketMaker.load(event.params.lmsrMarketMaker, {});
    context.contractRegistration.addLMSRMarketMaker(
      event.params.lmsrMarketMaker
    );
  }
);
```

![image](https://github.com/enviodev/envio-hyperindexer-issues/assets/45052332/16fa8803-853a-416c-bb36-85d7c5b44f53)

## Exceptions

```bash
GraphQL:
http://localhost:8080[18:08:29.728] ERROR (92205): EE901: Unexpected case. Contract name does not exist in interface mapping.
    RE_EXN_ID: "ContractInterfaceManager.UndefinedInterface/16"
    _1: "LMSRMarketMaker"



 ███████╗ ███╗   ██╗ ██╗   ██╗ ██╗  ██████╗ 
 ██╔════╝ ████╗  ██║ ██║   ██║ ██║ ██╔═══██╗
 █████╗   ██╔██╗ ██║ ██║   ██║ ██║ ██║   ██║
 ██╔══╝   ██║╚██╗██║ ╚██╗ ██╔╝ ██║ ██║   ██║
 ███████╗ ██║ ╚████║  ╚████╔╝  ██║ ╚██████╔╝
[18:08:29.729] ERROR (92205): Failed to fetch block Range
    chainId: 84532
    logType: "Block Range Query"
    workerType: "HyperSync"
    fromBlock: 7583593
    toBlock: 7583631
    addresses: [
      "0xD038ACB7543c8B0cc1E69531d9a4b2FE83Efdf43"
    ]
    fetchStateRegister: "dynamic-7583593-15"
    RE_EXN_ID: "ContractInterfaceManager.UndefinedInterface/16"
    _1: "LMSRMarketMaker"



 ███████╗ ███╗   ██╗ ██╗   ██╗ ██╗  ██████╗ 
 ██╔════╝ ████╗  ██║ ██║   ██║ ██║ ██╔═══██╗
 █████╗   ██╔██╗ ██║ ██║   ██║ ██║ ██║   ██║
 ██╔══╝   ██║╚██╗██║ ╚██╗ ██╔╝ ██║ ██║   ██║
 ███████╗ ██║ ╚████║  ╚████╔╝  ██║ ╚██████╔╝
 ╚══════╝ ╚═╝  ╚═══╝   ╚═══╝   ╚═╝  ╚═════╝ 


Events Processed: 0                    blocks:  7,583,593
                                               /8,098,910
⚡ Chain ID: 84532   0%                                  


Total events processed: 0
⠋ Calculating ETA...


GraphQL:
http://localhost:8080
/home/carlomigueldy/projects/limitless-labs-group/limitless-markets-indexer/node_modules/.pnpm/yoga-layout-prebuilt@1.10.0/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.10.0
```

![image](https://github.com/enviodev/envio-hyperindexer-issues/assets/45052332/a8460330-0caa-497d-87d0-d0c35d1fbe5d)

![image](https://github.com/enviodev/envio-hyperindexer-issues/assets/45052332/0129efcd-f743-4322-933c-28e8e34857df)

**Comment by carlomigueldy** [comment]
Resolved

It should also be registered under networks

```yaml
networks:
  - id: 84532 # Base Sepolia Testnet
    start_block: 7583453
    contracts:
      - name: LMSRMarketMakerFactory
        address: "0x5DAA869eB10B10fefaDA22773cC8b30A8744df87"
      - name: LMSRMarketMaker
```
